In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
from sklearn import tree
%matplotlib inline

df_census = pd.read_csv('census1994.csv')
print(df_census);
df = df_census.replace('[?]',np.nan,regex=True)
df_census = df.dropna(how='any')
print(df_census.shape)


             Date  Age          WorkClass  fnlwgt      education  \
0       3/20/1994   39          State-gov   77516      Bachelors   
1       1/14/1994   50   Self-emp-not-inc   83311      Bachelors   
2       8/14/1994   38            Private  215646        HS-grad   
3       3/17/1994   53            Private  234721           11th   
4       9/20/1994   28            Private  338409      Bachelors   
5      11/28/1994   37            Private  284582        Masters   
6        3/2/1994   49            Private  160187            9th   
7      11/27/1994   52   Self-emp-not-inc  209642        HS-grad   
8      12/25/1994   31            Private   45781        Masters   
9      10/10/1994   42            Private  159449      Bachelors   
10     10/29/1994   37            Private  280464   Some-college   
11     11/10/1994   30          State-gov  141297      Bachelors   
12       1/4/1994   23            Private  122272      Bachelors   
13      2/15/1994   32            Private  20501

In [2]:
first_five_recs = df_census.head();
print(first_five_recs);

        Date  Age          WorkClass  fnlwgt   education  education-num  \
0  3/20/1994   39          State-gov   77516   Bachelors             13   
1  1/14/1994   50   Self-emp-not-inc   83311   Bachelors             13   
2  8/14/1994   38            Private  215646     HS-grad              9   
3  3/17/1994   53            Private  234721        11th              7   
4  9/20/1994   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race   gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country   class  
0 

In [3]:
last_five_recs = df_census.tail();
print(last_five_recs);

             Date  Age      WorkClass  fnlwgt    education  education-num  \
32556  12/29/1994   27        Private  257302   Assoc-acdm             12   
32557   1/30/1994   40        Private  154374      HS-grad              9   
32558   9/26/1994   58        Private  151910      HS-grad              9   
32559    4/5/1994   22        Private  201490      HS-grad              9   
32560    3/5/1994   52   Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation relationship    race   gender  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loss  hours-per-week  nativ

In [4]:
for col in df_census.columns: 
    print(col)

Date
Age
WorkClass
fnlwgt
education
education-num
marital-status
occupation
relationship
race
gender
capital-gain
capital-loss
hours-per-week
native-country
class


In [5]:
#replacing string values with float values in dataframe to calculate euclidean distance:
df_c = df_census[['Age', 'education-num', 'class']].copy()
df_c['class']=df_c['class'].map({' <=50K': 0, ' >50K': 1, ' <=50K.': 0, ' >50K.': 1})

#Splitting the dataset 70% for training, and 30% for testing the classifier.

X = df_c.iloc[:, 0:3];
print(X);
Y = df_c.iloc[:, 0];
print(Y);

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3);
print (X_train);
print (Y_test);


       Age  education-num  class
0       39             13      0
1       50             13      0
2       38              9      0
3       53              7      0
4       28             13      0
5       37             14      0
6       49              5      0
7       52              9      1
8       31             14      1
9       42             13      1
10      37             10      1
11      30             13      1
12      23             13      0
13      32             12      0
15      34              4      0
16      25              9      0
17      32              9      0
18      38              7      0
19      43             14      1
20      40             16      1
21      54              9      0
22      35              5      0
23      43              7      0
24      59              9      0
25      56             13      1
26      19              9      0
28      39              9      0
29      49              9      0
30      23             12      0
31      20

In [6]:
clf_gini=DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth= None, min_samples_leaf=1) 
clf_gini.fit(X_train, Y_train) 


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [7]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth = None, min_samples_leaf = 1) 

clf_entropy.fit(X_train, Y_train) 


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [8]:
y_pred = clf_gini.predict(X_test)
y_pred

array([24, 42, 21, ..., 59, 21, 45], dtype=int64)

In [9]:
y_pred_en = clf_entropy.predict(X_test)
y_pred_en

array([24, 42, 21, ..., 59, 21, 45], dtype=int64)

In [10]:
print(confusion_matrix(Y_test,y_pred));

[[ 99   0   0 ...   0   0   0]
 [  0 150   0 ...   0   0   0]
 [  0   0 164 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   1   0]
 [  0   0   0 ...   0   0  15]]


In [11]:
print(classification_report(Y_test,y_pred));

              precision    recall  f1-score   support

          17       1.00      1.00      1.00        99
          18       1.00      1.00      1.00       150
          19       1.00      1.00      1.00       164
          20       1.00      1.00      1.00       194
          21       1.00      1.00      1.00       194
          22       1.00      1.00      1.00       205
          23       1.00      1.00      1.00       261
          24       1.00      1.00      1.00       233
          25       1.00      1.00      1.00       241
          26       1.00      1.00      1.00       215
          27       1.00      1.00      1.00       226
          28       1.00      1.00      1.00       251
          29       1.00      1.00      1.00       234
          30       1.00      1.00      1.00       227
          31       1.00      1.00      1.00       261
          32       1.00      1.00      1.00       234
          33       1.00      1.00      1.00       251
          34       1.00    

c:\users\sanju\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [12]:
print(confusion_matrix(Y_test,y_pred_en));

[[ 99   0   0 ...   0   0   0]
 [  0 150   0 ...   0   0   0]
 [  0   0 164 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   1   0]
 [  0   0   0 ...   0   0  15]]


In [13]:
print(classification_report(Y_test,y_pred_en)); 

              precision    recall  f1-score   support

          17       1.00      1.00      1.00        99
          18       1.00      1.00      1.00       150
          19       1.00      1.00      1.00       164
          20       1.00      1.00      1.00       194
          21       1.00      1.00      1.00       194
          22       1.00      1.00      1.00       205
          23       1.00      1.00      1.00       261
          24       1.00      1.00      1.00       233
          25       1.00      1.00      1.00       241
          26       1.00      1.00      1.00       215
          27       1.00      1.00      1.00       226
          28       1.00      1.00      1.00       251
          29       1.00      1.00      1.00       234
          30       1.00      1.00      1.00       227
          31       1.00      1.00      1.00       261
          32       1.00      1.00      1.00       234
          33       1.00      1.00      1.00       251
          34       1.00    

In [17]:
print ("Accuracy : ", 
    accuracy_score(Y_test,y_pred)*100)

Accuracy :  99.98894905514422
